SITES = [
    {"name": "anthropic-research",  "listing_urls": ["https://www.anthropic.com/research"],
     "article_url_pattern": r"anthropic\.com/research/[^/]+/?$",     "render_js": True},
    {"name": "anthropic-engineering","listing_urls": ["https://www.anthropic.com/engineering"],
     "article_url_pattern": r"anthropic\.com/engineering/.+",        "render_js": True},
    {"name": "anthropic-news",      "listing_urls": ["https://www.anthropic.com/news"],
     "article_url_pattern": r"anthropic\.com/news/.+",               "render_js": True},
    {"name": "openai-research",     "listing_urls": ["https://openai.com/research/index/"],
     "article_url_pattern": r"openai\.com/index/[^/]+/?$",           "render_js": True},
    {"name": "openai-index",        "listing_urls": ["https://openai.com/index/"],
     "article_url_pattern": r"openai\.com/index/[^/]+/?$",           "render_js": True},
    {"name": "google-research",     "listing_urls": ["https://research.google/blog/"],
     "article_url_pattern": r"research\.google/blog/[a-z0-9]+(?:-[a-z0-9]+)+/?$", "render_js": True},
    {"name": "deepmind",            "listing_urls": ["https://deepmind.google/blog/"],
     "article_url_pattern": r"deepmind\.google/blog/[a-z0-9]+(?:-[a-z0-9]+)+/?$", "render_js": True},
    {"name": "meta-ai",             "listing_urls": ["https://ai.meta.com/blog/"],
     "article_url_pattern": r"ai\.meta\.com/blog/[a-z0-9]+(?:-[a-z0-9]+)+/?$", "render_js": True},
    {"name": "huggingface",         "listing_urls": ["https://huggingface.co/blog"],
     "article_url_pattern": r"huggingface\.co/blog/[^/]+$",          "render_js": False},
    {"name": "microsoft-research",  "listing_urls": ["https://www.microsoft.com/en-us/research/blog/"],
     "article_url_pattern": r"microsoft\.com/en-us/research/blog/[a-z0-9]+(?:-[a-z0-9]+)+/?$","render_js": True},
    {"name": "mistral",             "listing_urls": ["https://mistral.ai/news/"],
     "article_url_pattern": r"mistral\.ai/news/[^/]+/?$",            "render_js": True},
    {"name": "cohere",              "listing_urls": ["https://cohere.com/blog"],
     "article_url_pattern": r"cohere\.com/blog/[^/]+$",              "render_js": False},
]
